  services:
    
    # library.api:
    #   image: library.api
    #   container_name: library-api
    #   build:
    #     context: .
    #     dockerfile: Library.Api/Dockerfile
    #   ports:
    #   - "5100:5100"
    #   - "7070:7070"
    #   depends_on:
    #   - db
    #   networks:
    #   - dev_network
    #   volumes:
    #     - ./book-images:/app/wwwroot/book-images

    db:
      image: mcr.microsoft.com/mssql/server:latest
      container_name: mssql-db
      ports:
        - "1433:1433"
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "DB_Password"
      networks:
        - dev_network
      volumes:
        - ./db-init/init.sql:/db/init.sql
        - ./db-init/entrypoint.sh:/entrypoint.sh
      entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
        
    library.cache:
      image: redis:latest
      container_name: redis-cache
      restart: always
      ports:
        - "6379:6379"
      networks:
        - dev_network
    
  networks:
    dev_network: